/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-22 18:55:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/workspace-spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test_ChoiJongHee/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1657512119371L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1656310637281L));
    _jspx_dependants.put("jar:file:/C:/workspace-spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test_ChoiJongHee/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("<!DOCTYPE html>	\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/MainStyle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("	 <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://use.fontawesome.com/releases/v6.1.1/js/all.js\"></script>\r\n");
      out.write("	 <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("        <section>\r\n");
      out.write("            <div id=\"place_cate\">\r\n");
      out.write("                <div class=\"place_circle\" onclick=\"location.href='../place/restaurants/list.jsp?'\">맛집</div>\r\n");
      out.write("                <div class=\"place_circle\" onclick=\"location.href='../place/festival/list.jsp?'\">명소</div>\r\n");
      out.write("                <div class=\"place_circle\" onclick=\"location.href ='../place/sights/list.jsp?'\">축제</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"menubox\">\r\n");
      out.write("                <ul id=\"menulist\">\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" id=\"star-view\" value=\"별점\" /></li>\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" id=\"visit\" value=\"방문횟수\" /></li>\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" id=\"steamed\" value=\"가장 많은 찜\" />\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" id=\"distance\" value=\"거리순\" /></li>\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" id=\"popularity\" value=\"인기순\" /></li>\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" id=\"festival\" value=\"축제\" /></li>\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" id=\"sights\" value=\"명소\" /></li>\r\n");
      out.write("                    <li><input type=\"button\" class=\"top10list\" onclick=\"listfocus()\" value=\"(TOP 10)\" disabled /></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"swiper-container\" id=\"star-first\">\r\n");
      out.write("                <h3 class=\"top10head\" id=\"star-view-focus\">별점 TOP 10</h3>\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star1\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\">\r\n");
      out.write("                                <span class=\"list-info-name\">이젠</span><span class=\"list-info-value\">⭐️</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star2\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star3\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star4\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star5\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star6\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star7\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star8\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star9\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"star10\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 양옆 좌우버튼 -->\r\n");
      out.write("                <div class=\"swiper-button-next Nbtn1\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev Pbtn1\"></div>\r\n");
      out.write("                <p class=\"view-more\"><a href=\"#\">더보기</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-container\" id=\"visit-second\">\r\n");
      out.write("                <h3 class=\"top10head\" id=\"visit-focus\">방문횟수 TOP 10</h3>\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit1\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit2\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit3\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit4\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit5\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit6\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit7\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit8\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit9\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"visit10\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"swiper-button-next Nbtn2\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev Pbtn2\"></div>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"view-more\"><a href=\"#\">더보기</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-container\" id=\"steamed-third\">\r\n");
      out.write("                <h3 class=\"top10head\" id=\"steamed-focus\">가장 많은 찜 TOP 10</h3>\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed1\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed2\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed3\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed4\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed5\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed6\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed7\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed8\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed9\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"steamed10\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-button-next Nbtn3\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev Pbtn3\"></div>\r\n");
      out.write("                <p class=\"view-more\"><a href=\"#\">더보기</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-container\" id=\"distance-fourth\">\r\n");
      out.write("                <h3 class=\"top10head\" id=\"distance-focus\">거리순 TOP 10</h3>\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance1\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance2\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance3\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance4\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance5\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance6\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance7\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance8\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance9\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"distance10\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-button-next Nbtn4\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev Pbtn4\"></div>\r\n");
      out.write("                <p class=\"view-more\"><a href=\"#\">더보기</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-container\" id=\"popularity-fifth\">\r\n");
      out.write("                <h3 class=\"top10head\" id=\"popularity-focus\">인기순 TOP 10</h3>\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity1\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity2\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity3\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity4\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity5\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity6\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity7\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity8\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity9\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image\" id=\"popularity10\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-button-next Nbtn5\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev Pbtn5\"></div>\r\n");
      out.write("                <p class=\"view-more\"><a href=\"#\">더보기</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-container\" id=\"festival-sixth\">\r\n");
      out.write("                <h3 class=\"top10head\" id=\"festival-focus\">축제 TOP 10</h3>\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival1\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival2\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival3\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival4\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival5\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival6\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival7\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival8\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival9\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image2\" id=\"festival10\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-button-next Nbtn6\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev Pbtn6\"></div>\r\n");
      out.write("                <p class=\"view-more\"><a href=\"#\">더보기</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"swiper-container\" id=\"sights-seventh\">\r\n");
      out.write("                <h3 class=\"top10head\" id=\"sights-focus\">명소 TOP 10</h3>\r\n");
      out.write("                <div class=\"swiper-wrapper\">\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights1\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights2\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights3\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights4\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights5\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights6\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights7\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights8\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights9\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-slide\">\r\n");
      out.write("                        <div class=\"slide-image3\" id=\"sights10\">\r\n");
      out.write("                            <div class=\"list-image\"></div>\r\n");
      out.write("                            <div class=\"list-info\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-button-next Nbtn7\"></div>\r\n");
      out.write("                <div class=\"swiper-button-prev Pbtn7\"></div>\r\n");
      out.write("                <p class=\"view-more\"><a href=\"#\">더보기</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("            $(document).ready(function () {\r\n");
      out.write("\r\n");
      out.write("                /* focus */\r\n");
      out.write("                $('#star-view').click(function () {\r\n");
      out.write("                    const offset = $('#star-view-focus').offset();\r\n");
      out.write("                    $('html').animate({ scrollTop: offset.top }, 400);\r\n");
      out.write("                });\r\n");
      out.write("                $('#visit').click(function () {\r\n");
      out.write("                    const offset = $('#visit-focus').offset();\r\n");
      out.write("                    $('html').animate({ scrollTop: offset.top }, 400);\r\n");
      out.write("                });\r\n");
      out.write("                $('#steamed').click(function () {\r\n");
      out.write("                    const offset = $('#steamed-focus').offset();\r\n");
      out.write("                    $('html').animate({ scrollTop: offset.top }, 400);\r\n");
      out.write("                });\r\n");
      out.write("                $('#distance').click(function () {\r\n");
      out.write("                    const offset = $('#distance-focus').offset();\r\n");
      out.write("                    $('html').animate({ scrollTop: offset.top }, 400);\r\n");
      out.write("                });\r\n");
      out.write("                $('#popularity').click(function () {\r\n");
      out.write("                    const offset = $('#popularity-focus').offset();\r\n");
      out.write("                    $('html').animate({ scrollTop: offset.top }, 400);\r\n");
      out.write("                });\r\n");
      out.write("                $('#festival').click(function () {\r\n");
      out.write("                    const offset = $('#festival-focus').offset();\r\n");
      out.write("                    $('html').animate({ scrollTop: offset.top }, 400);\r\n");
      out.write("                });\r\n");
      out.write("                $('#sights').click(function () {\r\n");
      out.write("                    const offset = $('#sights-focus').offset();\r\n");
      out.write("                    $('html').animate({ scrollTop: offset.top }, 400);\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                /* 클릭시 상세보기 페이지로 바로이동 */\r\n");
      out.write("                $('.slide-image').click(function () {\r\n");
      out.write("                    const id = document.getElementById;\r\n");
      out.write("                    location.href = \"../place/restaurants/view.jsp?restaurant_idx=\" + id.resturants_idx;\r\n");
      out.write("                });\r\n");
      out.write("                $('.slide-image2').click(function () {\r\n");
      out.write("                    const id = document.getElementById;\r\n");
      out.write("                    location.href = \"../place/festival/view.jsp?festival_idx=\" + id.festival_idx;\r\n");
      out.write("                });\r\n");
      out.write("                $('.slide-image3').click(function () {\r\n");
      out.write("                    const id = document.getElementById;\r\n");
      out.write("                    location.href = \"../place/sights/view.jsp?sights_idx=\" + id.sights_idx;\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("            document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("\r\n");
      out.write("                //initialize swiper when document ready\r\n");
      out.write("                // 별점 TOP 10\r\n");
      out.write("                const mySwiper = new Swiper('#star-first', {\r\n");
      out.write("                    slidesPerView: 3,       // 슬라이드 한번에 3개를 보여줌\r\n");
      out.write("                    slidesPerGroup: 3,      // 그룹으로 묶을 수\r\n");
      out.write("                    observer: true,\r\n");
      out.write("                    observeParents: true,\r\n");
      out.write("                    spaceBetween: 10,       // 슬라이드간 간격\r\n");
      out.write("                    // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("                    loopFillGroupWithBlank: true,\r\n");
      out.write("                    loop: false,    // true 할경우 무한반복\r\n");
      out.write("                    // Navigation arrows \r\n");
      out.write("                    navigation: {\r\n");
      out.write("                        nextEl: '.Nbtn1',\r\n");
      out.write("                        prevEl: '.Pbtn1',\r\n");
      out.write("                    },\r\n");
      out.write("                    // 반응형\r\n");
      out.write("                    breakpoints: {\r\n");
      out.write("                        1280: {\r\n");
      out.write("                            slidesPerView: 3,\r\n");
      out.write("                            slidesPerGroup: 3,\r\n");
      out.write("                        },\r\n");
      out.write("                        720: {\r\n");
      out.write("                            slidesPerView: 2,\r\n");
      out.write("                            slidesPerGroup: 2,\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                // 방문횟수 TOP 10\r\n");
      out.write("                const mySwiper2 = new Swiper('#visit-second', {\r\n");
      out.write("                    slidesPerView: 3,       // 슬라이드 한번에 3개를 보여줌\r\n");
      out.write("                    slidesPerGroup: 3,      // 그룹으로 묶을 수\r\n");
      out.write("                    observer: true,\r\n");
      out.write("                    observeParents: true,\r\n");
      out.write("                    spaceBetween: 10,       // 슬라이드간 간격\r\n");
      out.write("\r\n");
      out.write("                    // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("                    loopFillGroupWithBlank: true,\r\n");
      out.write("                    loop: false,    // true 할경우 무한반복\r\n");
      out.write("                    // Navigation arrows \r\n");
      out.write("                    navigation: {\r\n");
      out.write("                        nextEl: '.Nbtn2',\r\n");
      out.write("                        prevEl: '.Pbtn2',\r\n");
      out.write("                    },\r\n");
      out.write("                    // 반응형\r\n");
      out.write("					breakpoints: {\r\n");
      out.write("                        1280: {\r\n");
      out.write("                            slidesPerView: 3,\r\n");
      out.write("                            slidesPerGroup: 3,\r\n");
      out.write("                        },\r\n");
      out.write("                        720: {\r\n");
      out.write("                            slidesPerView: 1,\r\n");
      out.write("                            slidesPerGroup: 1,\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                // 가장 많은 찜 TOP10\r\n");
      out.write("                const mySwiper3 = new Swiper('#steamed-third', {\r\n");
      out.write("                    slidesPerView: 3,       // 슬라이드 한번에 3개를 보여줌\r\n");
      out.write("                    slidesPerGroup: 3,      // 그룹으로 묶을 수\r\n");
      out.write("                    observer: true,\r\n");
      out.write("                    observeParents: true,\r\n");
      out.write("                    spaceBetween: 10,       // 슬라이드간 간격\r\n");
      out.write("\r\n");
      out.write("                    // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("                    loopFillGroupWithBlank: true,\r\n");
      out.write("                    loop: false,    // true 할경우 무한반복\r\n");
      out.write("                    // Navigation arrows \r\n");
      out.write("                    navigation: {\r\n");
      out.write("                        nextEl: '.Nbtn3',\r\n");
      out.write("                        prevEl: '.Pbtn3',\r\n");
      out.write("                    },\r\n");
      out.write("                    breakpoints: {\r\n");
      out.write("                        1280: {\r\n");
      out.write("                            slidesPerView: 3,\r\n");
      out.write("                            slidesPerGroup: 3,\r\n");
      out.write("                        },\r\n");
      out.write("                        720: {\r\n");
      out.write("                            slidesPerView: 1,\r\n");
      out.write("                            slidesPerGroup: 1,\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                // 거리순 TOP 10\r\n");
      out.write("                const mySwiper4 = new Swiper('#distance-fourth', {\r\n");
      out.write("                    slidesPerView: 3,       // 슬라이드 한번에 3개를 보여줌\r\n");
      out.write("                    slidesPerGroup: 3,      // 그룹으로 묶을 수\r\n");
      out.write("                    observer: true,\r\n");
      out.write("                    observeParents: true,\r\n");
      out.write("                    spaceBetween: 10,       // 슬라이드간 간격\r\n");
      out.write("\r\n");
      out.write("                    // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("                    loopFillGroupWithBlank: true,\r\n");
      out.write("                    loop: false,    // true 할경우 무한반복\r\n");
      out.write("                    // Navigation arrows \r\n");
      out.write("                    navigation: {\r\n");
      out.write("                        nextEl: '.Nbtn4',\r\n");
      out.write("                        prevEl: '.Pbtn4',\r\n");
      out.write("                    },\r\n");
      out.write("                    // 반응형\r\n");
      out.write("                    breakpoints: {\r\n");
      out.write("                        1280: {\r\n");
      out.write("                            slidesPerView: 3,\r\n");
      out.write("                            slidesPerGroup: 3,\r\n");
      out.write("                        },\r\n");
      out.write("                        720: {\r\n");
      out.write("                            slidesPerView: 1,\r\n");
      out.write("                            slidesPerGroup: 1,\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                // 인기순 TOP 10\r\n");
      out.write("                const mySwiper5 = new Swiper('#popularity-fifth', {\r\n");
      out.write("                    slidesPerView: 3,       // 슬라이드 한번에 3개를 보여줌\r\n");
      out.write("                    slidesPerGroup: 3,      // 그룹으로 묶을 수\r\n");
      out.write("                    observer: true,\r\n");
      out.write("                    observeParents: true,\r\n");
      out.write("                    spaceBetween: 10,       // 슬라이드간 간격\r\n");
      out.write("\r\n");
      out.write("                    // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("                    loopFillGroupWithBlank: true,\r\n");
      out.write("                    loop: false,    // true 할경우 무한반복\r\n");
      out.write("                    // Navigation arrows \r\n");
      out.write("                    navigation: {\r\n");
      out.write("                        nextEl: '.Nbtn5',\r\n");
      out.write("                        prevEl: '.Pbtn5',\r\n");
      out.write("                    },\r\n");
      out.write("                    // 반응형\r\n");
      out.write("                    breakpoints: {\r\n");
      out.write("                        1280: {\r\n");
      out.write("                            slidesPerView: 3,\r\n");
      out.write("                            slidesPerGroup: 3,\r\n");
      out.write("                        },\r\n");
      out.write("                        720: {\r\n");
      out.write("                            slidesPerView: 1,\r\n");
      out.write("                            slidesPerGroup: 1,\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                // 축제 TOP 10\r\n");
      out.write("                const mySwiper6 = new Swiper('#festival-sixth', {\r\n");
      out.write("                    slidesPerView: 3,       // 슬라이드 한번에 3개를 보여줌\r\n");
      out.write("                    slidesPerGroup: 3,      // 그룹으로 묶을 수\r\n");
      out.write("                    observer: true,\r\n");
      out.write("                    observeParents: true,\r\n");
      out.write("                    spaceBetween: 10,       // 슬라이드간 간격\r\n");
      out.write("\r\n");
      out.write("                    // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("                    loopFillGroupWithBlank: true,\r\n");
      out.write("                    loop: false,    // true 할경우 무한반복\r\n");
      out.write("                    // Navigation arrows \r\n");
      out.write("                    navigation: {\r\n");
      out.write("                        nextEl: '.Nbtn6',\r\n");
      out.write("                        prevEl: '.Pbtn6',\r\n");
      out.write("                    },\r\n");
      out.write("                    // 반응형\r\n");
      out.write("                    breakpoints: {\r\n");
      out.write("                        1280: {\r\n");
      out.write("                            slidesPerView: 3,\r\n");
      out.write("                            slidesPerGroup: 3,\r\n");
      out.write("                        },\r\n");
      out.write("                        720: {\r\n");
      out.write("                            slidesPerView: 1,\r\n");
      out.write("                            slidesPerGroup: 1,\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                // 명소 TOP 10\r\n");
      out.write("                const mySwiper7 = new Swiper('#sights-seventh', {\r\n");
      out.write("                    slidesPerView: 3,       // 슬라이드 한번에 3개를 보여줌\r\n");
      out.write("                    slidesPerGroup: 3,      // 그룹으로 묶을 수\r\n");
      out.write("                    observer: true,\r\n");
      out.write("                    observeParents: true,\r\n");
      out.write("                    spaceBetween: 10,       // 슬라이드간 간격\r\n");
      out.write("\r\n");
      out.write("                    // 그룹수가 맞지 않을 경우 빈칸으로 메우기\r\n");
      out.write("                    loopFillGroupWithBlank: true,\r\n");
      out.write("                    loop: false,    // true 할경우 무한반복\r\n");
      out.write("                    // Navigation arrows \r\n");
      out.write("                    navigation: {\r\n");
      out.write("                        nextEl: '.Nbtn7',\r\n");
      out.write("                        prevEl: '.Pbtn7',\r\n");
      out.write("                    },\r\n");
      out.write("                    // 반응형\r\n");
      out.write("                    breakpoints: {\r\n");
      out.write("                        1280: {\r\n");
      out.write("                            slidesPerView: 3,\r\n");
      out.write("                            slidesPerGroup: 3,\r\n");
      out.write("                        },\r\n");
      out.write("                        720: {\r\n");
      out.write("                            slidesPerView: 1,\r\n");
      out.write("                            slidesPerGroup: 1,\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main/main.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/main/main.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/main.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
